#!/usr/bin/env ruby

require 'optparse'
require 'metron'
require 'metron/config'

# configuration
config = Config.new
parser = OptionParser.new
parser.on( '-c file' ) do |file|
  if ! File.exist? file then
    puts "fatal: Configuration file '#{file}' does not exists."
    exit false
  end

  config.set_config( file )
end
parser.parse!(ARGV)

# get library name
if ARGV.empty? then
  puts "fatal: The name of the library is not specified in the argument."
  exit false
end

name = ARGV.shift

if name.match(/\W/) then
  puts "fatal: The name of the library '#{name}' is invalid."
  exit false
end

# check env
path = Pathname.new( File.join( Dir.pwd, name ) )
if File.exists?( path ) then
  puts "fatal: Directory '#{name}' already exists"
  exit false
end

# run!
metronapp = MetronApp.new( name, config )

metronapp.create_library( Dir.getwd )

# create git repository
path = Pathname.new( File.join(Dir.getwd, name ) )
if `which git` != "" then
  Dir.chdir( path )
  status = IO.popen("git status", :err => [:child, :out])
  if ! status.include?( "fatal" ) then
    `git init`
  end
end
