#!/usr/bin/env ruby

require 'metron'

# library name
name = ARGV.shift

# check env
path = Pathname.new( File.join(Dir.pwd, name ) )
if File.exists?( path ) then
  raise "Directory #{name} is exists!"
end

# default dependent library
dependent_libraries = []

# default testing library
testing_libraries = [
  {
    :groupID          => "org.specs2",
    :artifactID       => "specs2-core",
    :is_scala_library => true,
    :version_style    => /^\d+\.\d+\.\d+$/
  }
]

# default sbt plugin
sbt_plugins = [
  {
    :groupID => "org.scoverage",
    :artifactID => "sbt-scoverage",
    :version_style => /^\d+\.\d+\.\d+$/
  },
]

metronapp = MetronApp.new(
  name,
  dependent_libraries: dependent_libraries,
  testing_libraries: testing_libraries,
  sbt_plugins: sbt_plugins
)

metronapp.create_library( Dir.getwd )

# create git repository
path = Pathname.new( File.join(Dir.getwd, name ) )
if `which git` != "" then
  Dir.chdir( path )
  status = IO.popen("git status", :err => [:child, :out])
  if ! status.include?( "fatal" ) then
    `git init`
  end
end


